import LegalLayout from "@/components/LegalLayout";

export const metadata = {
  title: "Privacy Policy — Functional Intelligence",
};

const CONTACT = process.env.NEXT_PUBLIC_CONTACT_EMAIL ?? "contact@funcimarket.com";

export default function Privacy() {
  return (
    <LegalLayout title="Privacy Policy" updated="July 13, 2026">
      <p>
        This Privacy Policy explains what Functional Intelligence
        (&ldquo;ƒi&rdquo;, &ldquo;we&rdquo;) collects, how we use it, and the
        choices you have. By using funcimarket.com you agree to this policy.
      </p>

      <h2>Information we collect</h2>
      <ul>
        <li>
          <strong>Email address</strong> &mdash; when you subscribe, back a
          topic, or commission a brief, so we can deliver briefs and
          confirmations.
        </li>
        <li>
          <strong>Name (optional)</strong> &mdash; a display name you may add to
          a backing. If provided, it may be shown publicly on The Board next to
          the topic you backed. Leave it blank to remain anonymous.
        </li>
        <li>
          <strong>Topic submissions</strong> &mdash; the papers, topics,
          questions, and links you submit, which appear publicly on The Board
          (private commissions excepted).
        </li>
        <li>
          <strong>Payment information</strong> &mdash; processed by Stripe. We
          do <strong>not</strong> collect or store your full card number; we
          receive limited transaction details (such as amount and a payment
          identifier) from Stripe.
        </li>
        <li>
          <strong>Basic technical data</strong> &mdash; standard server logs
          (e.g., IP address, request metadata) generated by our hosting
          provider for security and reliability.
        </li>
      </ul>

      <h2>How we use it</h2>
      <ul>
        <li>To deliver briefs and operate The Board and commissions.</li>
        <li>To process payments and prevent fraud and abuse.</li>
        <li>To communicate about the Service and respond to your requests.</li>
      </ul>
      <p>
        We do not sell your personal information, and we do not share your email
        address with other users. Your email is never displayed publicly.
      </p>

      <h2>Service providers</h2>
      <ul>
        <li>
          <strong>Stripe</strong> &mdash; payment processing.
        </li>
        <li>
          <strong>Supabase</strong> &mdash; database and storage.
        </li>
        <li>
          <strong>Vercel</strong> &mdash; website hosting.
        </li>
        <li>
          <strong>Substack</strong> (only if enabled) &mdash; if we use Substack
          to send briefs, your email may be added to that mailing list.
        </li>
      </ul>
      <p>
        These providers process data on our behalf under their own terms and
        security practices.
      </p>

      <h2>Data retention</h2>
      <p>
        We keep your information for as long as needed to run the Service and
        meet legal or accounting obligations. You may ask us to delete your
        email and personal data at any time (see below); we may retain limited
        transaction records as required by law.
      </p>

      <h2>Your choices and rights</h2>
      <p>
        You can unsubscribe from emails at any time. Depending on where you
        live, you may have rights to access, correct, or delete your personal
        information, or to object to certain processing. To exercise any of
        these, email <a href={`mailto:${CONTACT}`}>{CONTACT}</a> from the
        address on file and we will respond within a reasonable time.
      </p>

      <h2>Children</h2>
      <p>
        The Service is not directed to children under 16, and we do not
        knowingly collect their personal information.
      </p>

      <h2>Changes</h2>
      <p>
        We may update this policy; the &ldquo;Last updated&rdquo; date above
        reflects the latest version.
      </p>

      <h2>Contact</h2>
      <p>
        Questions or requests? Email{" "}
        <a href={`mailto:${CONTACT}`}>{CONTACT}</a>.
      </p>
    </LegalLayout>
  );
}
